- Gemfile
- Gemfile.lock
- spec/controllers/website_types_controller_spec.rb
- spec/controllers/websites_controller_spec.rb
small changes to fix deprecations
> fixes to deprecations

- config/routes.rb
- spec/factories/website_types.rb
- spec/requests/agencies_api_spec.rb
- Added tests for passing category_id to the endpoint
- Added icon field to the website_type
- Fixed indentation on routes.rb
> Agencies api2

- app/controllers/api/v1/agencies_controller.rb
- app/models/agency.rb
- spec/requests/agencies_api_spec.rb
- Added `icon` to websites and `lat`, `lng` to agencies in new_agency_hash
> New agencies api

- app/assets/stylesheets/messages.scss
- app/views/messages/index.html.erb
- config/locales/en.yml
- Add some pagination stylings on list of messages
> Pagination styling

- app/models/message.rb
- spec/factories/messages.rb
- spec/models/message_spec.rb
- Added Message model validations tests
> Message model tests

- app/controllers/agencies_controller.rb
- app/controllers/messages_controller.rb
- app/models/message.rb
- Fix it such that it displays the recently posted/updated message on homepage
> Display recently posted/updated message

- app/assets/stylesheets/messages.scss
- app/views/agencies/index.html.erb
- spec/features/messages_spec.rb
- Added user ability to remove message if they don't want it
- Added tests for display/removal of message by user
> Remove message

- app/views/agencies/_section2.html.erb
- app/views/agencies/index.html.erb
- app/views/layouts/_navigation_links.html.erb
- spec/features/messages_spec.rb
- Added `bell` icon on navbar to display the hidden message if users want to see it back again
- Added feature tests for it
> Bell on navbar

- app/models/agency.rb
- app/models/category.rb
- app/models/faq.rb
> Add back object ids for front end

- app/assets/javascripts/api/v1/devices.coffee
- app/assets/stylesheets/api/v1/devices.scss
- app/controllers/api/v1/devices_controller.rb
- app/controllers/application_controller.rb
- app/controllers/concerns/exception_handler.rb
- app/controllers/concerns/response.rb
- app/helpers/api/v1/devices_helper.rb
- app/models/device.rb
- bin/bundle
- bin/rails
- bin/rake
- bin/setup
- bin/update
- bin/yarn
- config/routes.rb
- db/migrate/20190812210352_create_devices.rb
- db/schema.rb
- spec/factories/devices.rb
- spec/models/device_spec.rb
- spec/requests/devices_spec.rb
- Added endpoint for registering a device
- Added device model test
- Added api endpoints/requests tests
@micronix !
> Device registration

- app/controllers/api/v1/devices_controller.rb
- Added skipping of authenticity token
@micronix !
> Skip authenticity token for create action

- app/controllers/messages_controller.rb
- app/views/messages/index.html.erb
- db/migrate/20190823205353_add_posted_at_to_messages.rb
- db/schema.rb
- Added a `posted_at` timestamp field to messages table
- Added admin ability to post/unpost a message only once
@micronix !
> Messages life cycle

- app/controllers/messages_controller.rb
- Added additional json field into messages array
@micronix !
> Add data field to messages array of hashes

- app/assets/javascripts/user_messages.coffee
- app/assets/stylesheets/user_messages.scss
- app/controllers/user_messages_controller.rb
- app/helpers/user_messages_helper.rb
- app/views/layouts/_navigation_links.html.erb
- app/views/user_messages/index.html.erb
- app/views/user_messages/show.html.erb
- config/routes.rb
- spec/features/messages_spec.rb
- Added templates to show `unposted` alert message history to users
- Created separate controller for `user_messages` with `index` and `show` actions and 
corresponding views
@jrmcgarvey @micronix 
Thank you!
> Alert history for users

- app/assets/stylesheets/agencies.scss
- app/assets/stylesheets/messages.scss
- app/controllers/user_messages_controller.rb
- app/views/agencies/_section3.html.erb
- app/views/agencies/show.html.erb
- Fixed phone icons display by using `if` statement
- Added some stylings as well
> Adding multiple phone numbers

- app/assets/stylesheets/pages.scss
- app/views/pages/privacy_policy.html.erb
- app/views/pages/terms_and_conditions.html.erb
- Improved mobile views of `Privacy Policy` and `Terms & Conditions`
- Made sure all tests pass after the change
@jrmcgarvey 
John, Lori requested that I make some changes on the pages so that it looks mobile friendly. Thanks!
> Improve mobile views 

- app/controllers/api/v1/devices_controller.rb
- app/controllers/messages_controller.rb
- db/migrate/20200128173356_add_selected_lang_to_devices.rb
- db/schema.rb
- spec/factories/devices.rb
- spec/requests/devices_spec.rb
- Added `selected_lang` field on Device model to allow mobile apps to select a language
- Refactored Device registration endpoint 
- Fixed failing requests tests
@jrmcgarvey @micronix 
Thank you!
> Push notifications translate

- app/controllers/faqs_controller.rb
- app/views/faqs/_form.html.erb
- app/views/faqs/edit.html.erb
- app/views/faqs/new.html.erb
- config/locales/en.yml
- config/locales/es.yml
- spec/controllers/faqs_controller_spec.rb
- Added `respuesta` field on the faq form partial
- Changed `text_field` input type to `text_area` in the faq form to allow multiple lines of text
@jrmcgarvey 
Thanks!
> Bug on faq creation

- app/controllers/agencies_controller.rb
- app/views/agencies/show.html.erb
- app/views/faqs/edit.html.erb
- app/views/faqs/index.html.erb
- app/views/faqs/new.html.erb
- app/views/user_messages/index.html.erb
- config/locales/en.yml
- config/locales/es.yml
- Made map `markers'` content clickable `links` for agencies
@jrmcgarvey 
Thanks!
> Add links to map content

- app/views/user_messages/index.html.erb
- config/locales/en.yml
- Changed `Direction` to `Address` on the English translation
@jrmcgarvey 
Thank you!
> Revert minor changes on english translations

- app/controllers/messages_controller.rb
Modified the post method to batch the notifications to 100 at a time.
Thanks @micronix !
> Modify post method for batch processing

- app/controllers/agencies_controller.rb
- app/models/agency.rb
- app/views/agencies/import.html.erb
- Fixed agency import bug by removing unnecessary commas in the code
- Fixed flash message (though it seems still misleading, eg. said 57 uploaded, but there are only 54 in db)
Thank you @micronix !!
> Fix agency import bugs

- app/controllers/agencies_controller.rb
- app/controllers/application_controller.rb
- app/controllers/categories_controller.rb
- app/views/agencies/index.csv.erb
- app/views/categories/index.csv.erb
- app/views/layouts/_navigation_links.html.erb
- Added an ability to `download` csv files of `agencies` and `categories` from web app as an admin
> Agency csv downloader

- app/assets/stylesheets/agencies.scss
- app/controllers/agencies_controller.rb
- app/models/agency.rb
- app/views/agencies/_section2.html.erb
- app/views/agencies/import.html.erb
- app/views/agencies/index.csv.erb
- app/views/agencies/new.html.erb
- app/views/layouts/_navigation_links.html.erb
- db/migrate/20210302183324_add_foreign_keys_to_agency_category.rb
- db/schema.rb
> Include websites categories in exports 

- app/models/agency.rb
> Comment out validation temporarily

- Gemfile
- Gemfile.lock
- config/initializers/airbrake.rb
> Add airbrake

- app/controllers/agencies_controller.rb
- app/views/agencies/index.csv.erb
- Fixed but on agency downloads
> Fix bug on agency downloads

- app/views/agencies/index.csv.erb
- Check if the category exists
> Fix first method

- app/controllers/agencies_controller.rb
- app/models/website.rb
- app/views/agencies/index.csv.erb
- Added map method in website model
> Add map method in Website model

- app/controllers/agencies_controller.rb
- app/controllers/categories_controller.rb
- app/controllers/faqs_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/users_controller.rb
- Changed update_attributes method
> Change update_attributes method

- app/models/agency.rb
- app/views/agencies/import.html.erb
- app/views/agencies/new.html.erb
- We do not associate `categories` if agency is not saved
- We do not create `websites` if agency is not save
Thanks @micronix
> Categories not associated and websites not added if agency is not saved

- app/models/agency.rb
- app/views/agencies/import.html.erb
- Added a table for created
Thank you @micronix !
> Add table for created agencies on import

- app/models/agency.rb
- db/migrate/20210525201118_add_county_and_nombre_to_agencies.rb
- db/schema.rb
- Include `county` and `nombre` in the `agencies` api endpoint response
> Nrai/return county and nombre on endpoint/CC-8

- db/migrate/20210525201118_add_county_and_nombre_to_agencies.rb
- db/schema.rb
- Added `county` and `nombre` columns to `agencies` table
Thank you @micronix
> Add county and nombre columns to agencies table

- app/controllers/agencies_controller.rb
- app/views/agencies/index.csv.erb
- db/migrate/20210525201118_add_county_and_nombre_to_agencies.rb
- db/schema.rb
- Include `county` and `nombre` in the agencies `export` sheet
> Nrai/include county and nombre in agencies export/CC-6

- app/controllers/agencies_controller.rb
- app/models/agency.rb
- config/locales/en.yml
- config/locales/es.yml
- db/migrate/20210525201118_add_county_and_nombre_to_agencies.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/agencies.rb
- Included `county` and `nombre` in the agencies import feature
Thanks @micronix
> Nrai/include county and nombre in agencies import/cc 5

- app/views/agencies/_section3.html.erb
- Display flash messages in `english` when locale is `en`
- Display flash messages in `spanish` when locale is `es`
Thanks @micronix
> Use locale to display flash messages in english and spanish conditionally

- app/views/agencies/_form.html.erb
- Added `nombre` and `county` in new/edit forms
> Add nombre and county in new and edit forms

- app/models/agency.rb
- Added `nombre` in the list of search names for agencies
> Add nombre in list of search names for agencies

- app/controllers/api/v1/agencies_controller.rb
- app/models/agency.rb
- Added an ability to `search` agencies by `county` from api endpoint
> nrai/agency search by county from endpoint/CC-9

- app/views/layouts/application.html.erb
> nrai/add saf ga code/cc-3

- config/locales/en.yml
- config/locales/es.yml
> Change the United States to North Carolina in the web app description

- app/controllers/agency_update_requests_controller.rb
- app/controllers/pages_controller.rb
- app/views/agencies/_section3.html.erb
- app/views/agencies/show.html.erb
- app/views/agency_update_requests/edit.html.erb
- app/views/agency_update_requests/new.html.erb
- app/views/pages/confirmation.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/routes.rb
- Changed button name from `Save` to `Submit`
- Changed link name from `Update` to `Submit Change`
- Redirected to a new page with message: `Organization update successfully submitted. An administrator will review your request.` after a change request is submitted
Thank you @micronix !
> Nrai/button and links stylings on agency updates/cc 41

- app/models/agency_update_request.rb
- Added geocoding on `agency update request` model
> Add geocoding to agency update request model

- app/models/agency.rb
- app/models/agency_county.rb
- app/models/county.rb
- db/migrate/20210831170007_create_counties.rb
- db/migrate/20210831170540_create_agency_counties.rb
- db/migrate/20210903024259_add_index_to_agency_counties_on_agency_id_and_county_id.rb
- db/schema.rb
- spec/factories/agency_counties.rb
- spec/factories/counties.rb
- spec/models/agency_county_spec.rb
- spec/models/county_spec.rb
- Created `counties` table with name, and state
- Created `agency_counties` join table which references `agency_id` and `county_id`
- Added validations and model associations for `agency`, `county`, and `agency_county` models
> nrai/create counties and agency counties tables/cc 44

- app/models/agency.rb
- app/models/agency_county.rb
- app/models/county.rb
- app/views/agencies/_section3.html.erb
- app/views/agencies/show.html.erb
- config/locales/en.yml
- config/locales/es.yml
- db/migrate/20210831170007_create_counties.rb
- db/migrate/20210831170540_create_agency_counties.rb
- db/migrate/20210903024259_add_index_to_agency_counties_on_agency_id_and_county_id.rb
- db/schema.rb
- spec/factories/agency_counties.rb
- spec/factories/counties.rb
- spec/models/agency_county_spec.rb
- spec/models/county_spec.rb
- Displayed list of `counties` from join table `agency_counties` for agencies in both index and show pages
- Changed County label to `Counties` and `Condados` for Spanish translations
**index.html.erb**
**show.html.erb**
> nrai/display list of counties for agencies/cc 46

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/controllers/agencies_controller.rb
- app/helpers/counties_helper.rb
- app/views/agencies/_form.html.erb
- app/views/agencies/index.html.erb
- Added `select2-rails` gem to list `counties` as `tags` when creating/updating `agencies`
Thanks @micronix
> nrai/autocomplete tag input field for counties/cc 45

- app/controllers/agencies_controller.rb
- app/helpers/counties_helper.rb
- app/views/agencies/index.html.erb
- Added agency search by `county` 
- Disabled `location` and `distance` input fields when `county` is selected from dropdown list and enabled when `All Counties` is selected from the top of the dropdown list
- Changed controller methods to fetch agencies from join table `agency_counties` 
https://user-images.githubusercontent.com/25111094/132880661-02a15d81-1db8-4ba7-b7dd-c9a189d29e6e.mov
> nrai/search agencies by counties/cc 47

- app/controllers/agency_update_requests_controller.rb
- app/policies/agency_update_request_policy.rb
- app/views/layouts/_navigation_links.html.erb
- config/locales/en.yml
- config/locales/es.yml
- Styled/improved `admin` dropdown for better user interface
- Added/modified Spanish and english translations
- Added `Sign out` link as well in the admin panel
Note: I branched off of my PR#58
> Nrai/style admin dropdown/cc 49

- Gemfile
- Gemfile.lock
- config/environments/staging.rb
> Add sengrid gems and staging file for mailer

- app/controllers/api/v1/agencies_controller.rb
- app/controllers/api/v1/counties_controller.rb
- app/models/agency.rb
- config/routes.rb
- Created separate `counties` endpoint so the app will load faster
- Removed `counties` object from `agencies` endpoint
Thank you @micronix
> Create an endpoint for counties

- app/controllers/agencies_controller.rb
- app/views/agencies/_form.html.erb
- Added a user option to select all `counties` when creating/updating an agency
https://user-images.githubusercontent.com/25111094/138023720-d712e294-d0c1-4ad9-95df-8887ee092837.mov
> Add user option to add all counties with a checkbox on create/update

- db/seeds.rb
- Added `save` method to save counties from the csv file
> Save county from csv file

- app/controllers/api/v1/messages_controller.rb
- app/models/device.rb
- app/models/message.rb
- config/routes.rb
- Created an endpoint to `create` device messages by passing `device_id`, `message_id`, and `ticket_id`
- Used `Postman` to test the endpoint
https://user-images.githubusercontent.com/25111094/143054949-5b22b1d1-43af-482b-9602-b20ac112b4c5.mov
> Add an endpoint to create device messages

- app/controllers/api/v1/messages_controller.rb
- Modified code logic to record all `devices` from where the `message` is `read`
Thank you @micronix !
> Modify logic not to restrict message read to only one device

- app/assets/stylesheets/application.css.scss
- app/views/agency_update_requests/index.html.erb
- Display `date` and `time` of when an `agency update request` was created right next to the `name` of the person that submitted the `request`
- Removed lines of code that was `commented out` earlier
Thank you @micronix !!
> nrai/display date and time to agency update request/cc 77

- app/assets/stylesheets/agencies.scss
- app/controllers/agencies_controller.rb
- app/controllers/api/v1/counties_controller.rb
- app/views/agencies/index.html.erb
- spec/controllers/agencies_controller_spec.rb
- Improved user's ability to search agencies by typing a few letters for a county with fuzzy search and display suggested shortened list of `counties` in the dropdown
https://user-images.githubusercontent.com/25111094/138950649-73f060a0-b101-4993-8b83-5d67bb7597ee.mov
> Improve agency search by counties by adding user ability to type a letter or two

- app/views/agencies/_section3.html.erb
- app/views/agencies/show.html.erb
- Added a logic to display agency `name` on `index` page when `nombre` is `nil` or `blank`
- Added a logic to display agency `name` on `show` page when `nombre` is `nil` or `blank`
> Display agency name when nombre is blank or does not exist
